### ISSUE TITLE
Username and password only working for 1 login ?

### ISSUE THREAD

**Issue by NicTanghe** [EmberLightVFX/Kitsu-for-Docker#3]
Hello the supplied username and password seem to be incorrect.

admin@example.com
mysecretpassword

I have tried on both firefox and edge.

**Comment by NicTanghe** [comment]
deleting initialised.txt and restarting the application did not help.

edit:
Just deleting initialised without restarting did help.

after logging off i cant log in with anny user on anny acount.

**Comment by albertjohnsonpc** [comment]
got the same issue here

**Comment by vishalkadam47** [comment]
would it be possible to expose the credentials via env variables

**Comment by DangerDrome** [comment]
yeah this is not working (can't login)

**Comment by NicTanghe** [comment]
I think that's just how they get u to pay for support. which is fine.
I'm looking at making a rust based alternative.

**Comment by Aiacos** [comment]
Hi, same here, unable to login after install

**Comment by EmberLightVFX** [comment]
Please note that this docker image have nothing to do with CGWire (creators of Zou, Gazu and Kitsu) and is created by me for ease of publishing.
I currently don't have much time to debug what's going on, especially as the image works for me.

If you want help, please send logs from all the images deployed that might give a hint on what's going on.

What you can try is remove the initialized.txt file in the previews folder and first restart postgres and then restart zou/kitsu.

PRs to fix this problem is more than welcome

**Comment by Aiacos** [comment]
Looks like init_zou.sh is not executed
this in the terminal fix the issue:
docker exec -it cgwire-zou-app /bin/bash
zou upgrade-db
zou init-data
zou create-admin admin@example.com --password mysecretpassword
exit

**Comment by vishalkadam47** [comment]
Logs
```
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/__init__.py", line 93, in list_pairings
    return await get_pairing_list(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/pairing_list.py", line 23, in get_pairing_list
    kitsu_projects_response = await addon.kitsu.get("data/projects")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 91, in get
    return await self.request("get", endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 77, in request
    await self.ensure_login()
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 45, in ensure_login
    await self.login()
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 31, in login
    raise KitsuLoginException("Could not login to Kitsu (invalid credentials)")
kitsu-1-2-3.kitsu.kitsu.KitsuLoginException: Could not login to Kitsu (invalid credentials)
2024-10-31 11:29:31 ERROR      anonymous       [GET] /addons/kitsu/1.2.3/pairing: UNHANDLED EXCEPTION
2024-10-31 11:29:31 ERROR      server          Could not login to Kitsu (invalid credentials)
[2024-10-31 11:29:31 +0000] [657] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/__init__.py", line 93, in list_pairings
    return await get_pairing_list(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/pairing_list.py", line 23, in get_pairing_list
    kitsu_projects_response = await addon.kitsu.get("data/projects")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 91, in get
    return await self.request("get", endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 77, in request
    await self.ensure_login()
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 45, in ensure_login
    await self.login()
  File "/addons/kitsu/1.2.3/server/kitsu/kitsu.py", line 31, in login
    raise KitsuLoginException("Could not login to Kitsu (invalid credentials)")
kitsu-1-2-3.kitsu.kitsu.KitsuLoginException: Could not login to Kitsu (invalid credentials)
```

**Comment by EmberLightVFX** [comment]
How does your docker compose look like?

**Comment by albertjohnsonpc** [comment]
> How does your docker compose look like?

At first I used bind mounts for the volumes and I think that was the problem, after switching to docker volumes it worked for me.
Been using this for a month in production, no issues so far. Not sure why the bind mounts are not working.
Thanks.

**Comment by EmberLightVFX** [comment]
Weird. I'm myself is using bind mounts. Good to know it's working for you now!
